# @package _global_
defaults:
  - /models/flux/klein9bkv@model
  - _self_

_target_: infusers.quant.flux.image.FluxImageQuant
num_steps: 4
guidance: 1.0
resolution: [1024, 1024]
cpu_offload: true
model:
  config:
    load_flow_on_cpu: true
